version: "3"
services:
  web:
    build: .
    ports:
    - '8080:80'
    volumes:
    - ./public:/var/www/html
    - logs:/var/log
    links:
    - redis
  redis:
    image: redis
    volumes:
      logs: {}
